fj_2024_lesson_2. Создана реализация программы по конвертации JSON файла в POJO и из POJO в XML файл.
Therenegadee/fintech-2024 pull request #2
Opened 2024-08-31 09:38 UTC by Therenegadee

2024-09-06 07:16 UTC, engarik requested changes
Привет!
В целом код хорошо написан, поправь небольшие замечания, чтобы я мог зачесть на полный балл

2024-09-06 07:16 UTC, engarik commented on src/main/java/ru/tbank/model/City.java
> +import lombok.*;
Лучше не использовать wildcard импорты, а сразу заменять их на конкретные импорты

2024-09-06 07:16 UTC, engarik commented on src/main/java/ru/tbank/util/JsonConverter.java
> +            log.error("В процессе конвертации JSON файла в POJO объект класса {} произошла ошибка и он не был десериализован.",
Поменяй уровень на warn.
1. В задании есть формальное требование на использование 4-ёх уровней логгирования.
2. Согласно твоей логике, программа может продолжить работу, даже если десериализация не удалась, это можно считать warn уровнем.

2024-09-07 07:29 UTC, Therenegadee commented on src/main/java/ru/tbank/util/JsonConverter.java
> +            log.error("В процессе конвертации JSON файла в POJO объект класса {} произошла ошибка и он не был десериализован.",
Привет! Поправил.

2024-09-11 18:32 UTC, engarik approved these changes
GJ, принято ✅

2024-09-25 09:30 UTC, merged